name: aws_trip_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_flutter: ^1.0.0
  amplify_storage_s3: ^1.0.0

  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.3
  go_router: ^14.2.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.8.3
  riverpod_annotation: ^2.0.1
  uuid: ^4.4.2

  build_runner:
  custom_lint:

  riverpod_generator: ^2.1.3
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
  assets:
    - images/amplify.png